### ISSUE TITLE
Extend session duration before needing to reload webapp

### ISSUE THREAD

**Issue by benjamin-merkel** [MathMarEcol/WSMPA2#124] opened 2022-09-08 13:41 UTC
Is it possible to have a longer session without reloading immidiatly? (comment from NP managers)

**Comment by jaseeverett** [comment] 2022-09-09 01:13
No. It is currently set to 15 mins which is the max allowed time. But that is 15 mins of idle time (from last button press) so it should be heaps. 
Have you seen evidence of it not working properly or being shorter?

**Comment by benjamin-merkel** [comment] 2022-09-09 06:21
Well that is weird. I agree that 15 min is plenty. We went through some stuff on the app yesterday in a meeting and got much shorter (perceived) reloading times. Could it be connected to the amount of devices using a server simultaneously?

**Comment by jaseeverett** [comment] 2022-09-09 08:23
It could have been a separate error which caused the disconnect. I will see if I can recreate.

Shiny can't distinguish between a timeout or another error.

**Comment by jaseeverett** [comment] 2022-09-12 10:17
I can't reproduce. 

Closing this issue. Reopen if it becomes a problem again

**Closed by jaseeverett** 2022-09-12 10:17 UTC
Labels: NPI

**Comment by benjamin-merkel** [comment] 2022-09-12 10:21
One possible reason might be that sessions are canceled whenever you update something. However, I also did experience it a couple of times that i get the reload button approx. 2 minutes into using the app.
